# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'ubuntu-latest'

variables:
  VERSION: '$(build.buildNumber)'
  DOCKER_REGISTRY: $(dockerId).azurecr.io

steps:
- script: sudo service docker status
  displayName: 'docker status'

- script: docker-compose -f ./AKS/docker-compose.yml -f ./AKS/docker-compose.override.yml --project-directory ./AKS build
  displayName: 'docker-compose build'

- script: |
    echo "$(dockerPassword)" | docker login  $(dockerId).azurecr.io -u $(dockerUsername) --password-stdin
    docker push $(dockerId).azurecr.io/$(dockerId).azurecr.io-helloworld:$(VERSION)
    docker push $(dockerId).azurecr.io/$(dockerId).azurecr.io-helloworldnode:$(VERSION)
    docker push $(dockerId).azurecr.io/$(dockerId).azurecr.io-web:$(VERSION)    
  displayName: "docker publish"
  
- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)/Kube/
    contents: '**/*.*'
    targetFolder: $(Build.ArtifactStagingDirectory)/Kube/
    
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactsName: 'drop'
 